Hacktoberfest2022
python-spain/web-ng pull request #120
Opened 2022-10-06 11:18 UTC by LcTrKiD

@astrojuanlu porfa review :)

2022-10-06 12:06 UTC, astrojuanlu requested changes
¡Me gusta mucho! Gracias @LcTrKiD por arrancar. He hecho algunas recomendaciones rápidas de estilo, estoy pensando si reestructurarlo un poco más.

2022-10-06 12:06 UTC, astrojuanlu commented on src/content/posts/2022-10-06-hacktoberfest-2022.md
> +Como cada Octubre, las hojas de los arboles empiezan a caerse y llega el Hacktoberfest.
Jaj, me encanta este inicio 😄 

```suggestion
Como cada Octubre, las hojas de los árboles empiezan a caerse y llega el Hacktoberfest.
```

2022-10-06 12:06 UTC, astrojuanlu commented on src/content/posts/2022-10-06-hacktoberfest-2022.md
> +Este año, aun empezando con unos días de demora, no queremos dejar de apoyar una vez más los eventos Hacktoberfest que realicen nuestras comunidades locales.
No hace falta pedir perdón yo creo:

```suggestion
Un año más varias comunidades locales están preparando eventos para celebrar Hacktoberfest, ¡y desde Python España queremos apoyarlos!
```

2022-10-06 12:06 UTC, astrojuanlu commented on src/content/posts/2022-10-06-hacktoberfest-2022.md
> +Para ello queremos compartir con todas vosotras una serie de recomendaciones para vuestros eventos locales:
```suggestion
Para ello queremos compartir con todas vosotras una serie de recomendaciones:
```

2022-10-06 12:06 UTC, astrojuanlu commented on src/content/posts/2022-10-06-hacktoberfest-2022.md
> +- Preparad un código de conducta que facilite la diversidad y mantenga una atmósfera en la que cualquier persona sea bienvenida. Aquí podéis echar un ojo a nuestro [código de conducta](https://2022.e
```suggestion
- Elaborad una agenda del evento. Es importante que la gente nueva entienda en qué va a consistir el evento.
- Proponed una fecha una vez sepáis que todas las personas implicadas en el evento como organizadoras y ponentes podrán acudir.
- Promoved vuestro evento e invitad a cualquier persona que pueda estar interesada en aprender y/o contribuir al open source.
- Adoptad un código de conducta que facilite la diversidad y mantenga una atmósfera en la que cualquier persona sea bienvenida. Aquí podéis echar un ojo a nuestro [código de conducta](https://es.python.org/codigo-conducta/).
```

2022-10-06 12:06 UTC, astrojuanlu commented on src/content/posts/2022-10-06-hacktoberfest-2022.md
> +Como muchas sabréis Hacktoberfest es un evento promovido por [DigitalOcean](https://www.digitalocean.com/) y [Hacktoberfest](https://twitter.com/hacktoberfest). Si queréis hacer un evento oficial pod
```suggestion
Hacktoberfest es un evento promovido por la empresa [DigitalOcean](https://www.digitalocean.com/). Para que el evento aparezca en la web oficial, tenéis que rellenar [este formulario](http://bit.ly/hacktoberfest-22-events) que provee la propia organización.
```

2022-10-06 12:29 UTC, LcTrKiD commented
@astrojuanlu todas las sugerencias aceptadas y comiteadas!

2022-10-07 17:11 UTC, LcTrKiD commented
Se necesita algo más para aceptar el PR?

2022-10-07 18:47 UTC, astrojuanlu approved these changes
¡Publiquémoslo así!

2022-10-07 18:48 UTC, astrojuanlu commented
No sé si es el equipo correcto pero ping  @python-spain/equipo-editor

2022-10-07 23:42 UTC, merged