section created with the content of the old website
python-spain/web-ng pull request #29
Opened 2021-07-27 14:42 UTC by jagtrrz

2021-07-28 06:32 UTC, dukebody requested changes
- quitar el `console.log`
- enlace a actas, etc. integrado
- "quiénes somos" con acento

2021-07-28 06:32 UTC, dukebody commented on src/components/Menu.js
> +  console.log(data)
mejor quitar esto :D

2021-07-28 06:32 UTC, dukebody commented on src/content/basic/about-us.md
> +https://github.com/python-spain/documentacion/
mejor poner esto como enlace en la frase anterior. Usa https://www.markdownguide.org/basic-syntax/#links

2021-07-28 06:32 UTC, dukebody commented on src/data/menus/mainMenu.json
> +        "name": "Quienes somos",
acento en quiénes :)

2021-07-28 06:44 UTC, jagtrrz commented on src/components/Menu.js
> +  console.log(data)
Ok. Lo quito

2021-07-28 06:44 UTC, jagtrrz commented on src/data/menus/mainMenu.json
> +        "name": "Quienes somos",
Ok

2021-07-28 06:44 UTC, jagtrrz commented on src/content/basic/about-us.md
> +https://github.com/python-spain/documentacion/
en cual exactamente?

2021-07-29 06:25 UTC, dukebody commented on src/content/basic/about-us.md
> +https://github.com/python-spain/documentacion/
Algo tipo `Puedes acceder a los estatutos, reglamento de régimen interno, actas y otra documentación [aquí](https://github.com/python-spain/documentacion/).`

2021-07-31 17:41 UTC, dukebody approved these changes
¡Pinta bien lo del plugin!

Si puedes hacer lo que te indico antes del merge mejor. No hace falta que vuelvas a pedir review. :)

2021-07-31 17:41 UTC, dukebody commented on src/content/basic/about-us.md
> +https://github.com/python-spain/documentacion/
Al final no hiciste esto, ¿no?

2021-07-31 17:42 UTC, cmaureir commented
Pues aparte de los comentarios de Isra, no veo más cosillas que se puedan mejorar.

2021-07-31 17:43 UTC, dukebody commented
Por cierto, ¿has comprobado si el plugin funciona? Es decir, si pone el target=blank a los enlaces externos dentro del markdown.

2021-07-31 17:51 UTC, dukebody requested changes
está dos veces listado `gatsby-transformer-remark`

2021-07-31 17:51 UTC, dukebody commented on gatsby-config.js
> +      resolve: `gatsby-transformer-remark`,
Uy, creo que esto no está bien. Probablemente tengas que cambiar el `'gatsby-transformer-remark',` (línea 11 más arriba) por esto, en vez de volver a listar este plugin, ya que estaría duplicado.

2021-08-03 16:10 UTC, jagtrrz commented on src/content/basic/about-us.md
> +https://github.com/python-spain/documentacion/
Se me paso. Lo vuelvo a subir

2021-08-03 16:17 UTC, jagtrrz commented on gatsby-config.js
> +      resolve: `gatsby-transformer-remark`,
ya veo... no se copie y pegue de la documentación del propio plugin y cambie el target. 

Por cierto funciona perfectamente, si le pinchas te abre en una nueva ventana y en el inpsector puedes ver el html con el target _blank. 
![imagen](https://user-images.githubusercontent.com/75372070/128050386-84338f20-d77d-41a7-83ed-26a4a6d6d11f.png)
![imagen](https://user-images.githubusercontent.com/75372070/128050419-da4dc0c8-72bd-4a82-a285-b1842f969360.png)

2021-08-03 16:43 UTC, merged