Feature/stefano/mainpage
python-spain/web-ng pull request #61
Opened 2021-09-02 09:33 UTC by stefanobelfiore

acabado parte hazte socio y foto pagina, averiguar si gusta la foto o cambiar el fichero de la imagen si se quiere cambiar. El componente de la imagen ya está hecho

2021-09-05 12:35 UTC, dukebody requested changes
- Utiliza la técnica de `background-image` para esta imagen estilo "hero" en lugar de poner la imagen directamente. Esto hace que sea más sencillo ponerle el estilo.
- La imagen utilizada actualmente pesa +1MB, lo que es demasiado para muchas conexiones. Intenta optimizarla recortándola, haciéndola más pequeña y quitándole colores. Ejemplo: https://www.lauraleeflores.com/blog/header-image-sizing-guide  También tiene sentido poner una imagen más pequeña y con menos resolución para la versión móvil.
- No incluyas en este PR cambios de otras cosas. Por ejemplo veo que hay cambios de comunidades locales, hazte socio... esto mejor en otro PR si fuese necesario.

2021-09-05 12:35 UTC, dukebody commented on src/components/MapData.js
> +import { Marker, Popup } from 'react-leaflet'
todo esto no pertenece aquí :sweat_smile:

2021-09-05 12:35 UTC, dukebody commented on src/content/basic/hazte-socio.md
> +---
Mejor poner esto en otro PR y no mezclar cosas. Si no, es mucho más lío de revisar y llevar el registro de cambios.

2021-09-05 12:35 UTC, dukebody commented on src/pages/index.js
> +            {/* {services.length > 0 && (
No comentes las cosas, mejor bórralas. Si queremos los originales, siempre podemos tirar de la historia de git o del theme original.

2021-09-05 12:35 UTC, dukebody commented on src/scss/style.scss
> +  body {
Como te comenté en la llamada ésta es una forma bastante rara de arreglar el tema responsive. Lo ideal sería poner la imagen hero como un background-image de un nodo bloque (div) y así se ajustaría automáticamente.

2021-09-05 12:35 UTC, dukebody commented on src/components/Image.js
> +    return <StaticImage
Es más sencillo poner la imagen como un background-image.

Puedes utilizar https://www.gatsbyjs.com/plugins/gatsby-background-image/ para esto.

Ejemplo: https://www.w3schools.com/howto/howto_css_hero_image.asp  Pero puedes encontrar muchas más páginas donde describen cómo hacerlo, con muchos efectos chulos.

2021-09-05 12:35 UTC, dukebody commented on src/pages/team.js
> -import Call from '../components/Call';
Entiendo que esto no hace falta tenerlo aquí, pero mejor borrarlo en otro PR para no liar. :)

2021-09-19 16:27 UTC, dukebody commented
@stefanobelfiore sé que te dije yo de usar esta foto y difuminar las caras, pero ahora que lo veo quizá no queda bien del todo. Parece que hace más énfasis en el edificio y los árboles que la gente, que apenas se ve:
![image](https://user-images.githubusercontent.com/41953/133935013-bfdd976b-d49e-4af7-a107-ff68bbc8bcc4.png)

El texto del Call for Action (únete) no puede estar empotrado en la imagen, sino que debería ser un botón separado encima, como puedes ver en casos como [éste](https://i.pinimg.com/originals/8a/3e/07/8a3e072ca16e3d121f081dfac26ed419.png). De hecho ahora mismo el texto sólo se ve si se hace más estrecha la pantalla.

De todas formas, al hacerla más estrecha se ve solamente un lado, en vez de verse centrada que creo que quedaría más natural. Mira: 
![image](https://user-images.githubusercontent.com/41953/133935152-ae462a24-9c9d-4db3-988e-381118425297.png)

Igualmente creo que en la versión "tablet" la imagen debería ser más pequeña. Ahora mismo no se hace más pequeña hasta que llegas a tamaño móvil, que queda algo raro.

2021-09-19 16:34 UTC, dukebody requested changes
- Ahora mismo la imagen no queda bien. Mira mis comentarios en el PR en un comentario anterior.
- Quita los cambios que no pertenecen a este PR.
- El tema del CSS aplicado directamente al `body` es bastante raro. ¿Puedes revisarlo?
- Pon el CSS de la imagen en un archivo SCSS separado.
- No necesitamos los plugins de Gatsby que has instalado. ¿O sí?

2021-09-19 16:34 UTC, dukebody commented on src/scss/style.scss
> +@media only screen and (max-width: 500px) {
Mejor poner este CSS en un archivo específico para el componente de la imagen en vez de directamente aquí. Así quedaría más modular y recogidito.

2021-09-19 16:34 UTC, dukebody commented on src/scss/style.scss
> +  body {
¿Has revisado esto?

2021-09-19 16:34 UTC, dukebody commented on gatsby-config.js
> +    `gatsby-transformer-sharp`,
¿Realmente necesitamos estos plugins para la forma en la que has hecho la feature? Porque veo que simplemente mencionas una ruta en un SCSS, no usas ninguna de las features de transformación de imágenes de Gatsby.

2021-09-19 19:27 UTC, stefanobelfiore commented on gatsby-config.js
> +    `gatsby-transformer-sharp`,
Antes lo hice con el componente StaticImage y luego cuando me dijiste del div lo hice con un background image..el plugin ya no hace falta ahora

2021-09-19 19:29 UTC, stefanobelfiore commented on src/components/MapData.js
> +import { Marker, Popup } from 'react-leaflet'
Esto tiene que estar en ese componente porque cada sede que se crea con el map del diccionario de las comunidades contiene cada uno un marker y un popup

2021-09-19 19:33 UTC, stefanobelfiore commented on src/scss/style.scss
> +  body {
No conseguí hacerlo de otra manera..el problema es el tamaño del body y no he conseguido de ninguna otra manera de editarlo que no sea esta

2021-09-24 17:55 UTC, dukebody commented on gatsby-config.js
> +    `gatsby-transformer-sharp`,
¿Ok, lo podrías quitar entonces?

2021-09-24 17:56 UTC, dukebody commented on src/scss/style.scss
> +  body {
@carmeco ¿tienes idea tú de cómo conseguirlo?

2021-09-24 17:57 UTC, dukebody commented on src/components/MapData.js
> +import { Marker, Popup } from 'react-leaflet'
Ya, me refiero que añadir este archivo no debería formar parte de este PR. Este PR tiene cosas mezcladas de varias features y la del mapa ya estaba mergeada. ¿Podrías transplantar sólo los cambios de la imagen a una rama nueva?

2021-09-27 11:27 UTC, closed without merging